// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5gTNM3aFOw38u2oQ1WjrxSMJVfk9m5p8',
    appId: '1:675212591530:web:0a871840624cd12b98ebd3',
    messagingSenderId: '675212591530',
    projectId: 'chat-app-f91e1',
    authDomain: 'chat-app-f91e1.firebaseapp.com',
    storageBucket: 'chat-app-f91e1.appspot.com',
    measurementId: 'G-T5S76VMGLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVVFUo4Ot5B08vG69hfDBF4jvHH1gfBFQ',
    appId: '1:675212591530:android:1eba3b66e04d8d2998ebd3',
    messagingSenderId: '675212591530',
    projectId: 'chat-app-f91e1',
    storageBucket: 'chat-app-f91e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc_-1mL1Pk_Q_qX-C1g7imYGq1O1FoKTA',
    appId: '1:675212591530:ios:ac3f2adb7e519e2398ebd3',
    messagingSenderId: '675212591530',
    projectId: 'chat-app-f91e1',
    storageBucket: 'chat-app-f91e1.appspot.com',
    iosClientId: '675212591530-5gah2p4ku5lorlit2e5vkht24d6e7ne0.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc_-1mL1Pk_Q_qX-C1g7imYGq1O1FoKTA',
    appId: '1:675212591530:ios:2a0cb268b579549098ebd3',
    messagingSenderId: '675212591530',
    projectId: 'chat-app-f91e1',
    storageBucket: 'chat-app-f91e1.appspot.com',
    iosClientId: '675212591530-1mh32b73t2gp3vh8mg38j5ml7o8q9sl5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
